### BGM

define bgm.another_day = "audio/bgm/another_day.ogg"
define bgm.bad_ending = "audio/bgm/bad_ending.ogg"
define bgm.title = "audio/bgm/title.ogg"
define bgm.lethal_suspense = "audio/bgm/lethal_suspense.ogg"
define bgm.reckoning_I = "audio/bgm/reckoning_I.ogg"
define bgm.reckoning_II = "audio/bgm/reckoning_II.ogg"
define bgm.marching_forward = "audio/bgm/marching_forward.ogg"
define bgm.something_amiss = "audio/bgm/something_amiss.ogg"

#ambience
define bgm.village_ambience = "audio/bgm/village_ambience.ogg"
define bgm.village_ambienceLoop = "audio/bgm/village_ambienceLoop.ogg"
define bgm.night_ambience = "audio/Ambience/night_ambience.ogg"
define bgm.dungeon_ambience = "audio/Ambience/dungeon_ambience.ogg" 
define bgm.altar_ambience = "audio/Ambience/altar_ambience.ogg" 

### SFX

define sfx.bam = "audio/sfx/bam.ogg"
define sfx.block = "audio/sfx/block.ogg"
define sfx.bloodfootsteps = "audio/sfx/bloodfootsteps.ogg"
define sfx.bloodlance = "audio/sfx/bloodlance.ogg"
define sfx.blood_splatter = "audio/sfx/blood_splatter.ogg"
define sfx.bone_break = "audio/sfx/bone_break.ogg"
define sfx.bottle_open = "audio/sfx/bottle_open.ogg"
define sfx.bubble1 = "audio/sfx/bubble1.ogg"
define sfx.bubble2 = "audio/sfx/bubble2.ogg"
define sfx.charm = "audio/sfx/charm.ogg"
define sfx.crash = "audio/sfx/crash.ogg"  
define sfx.dagger_draw = "audio/sfx/dagger_draw.ogg"
define sfx.door_break = "audio/sfx/door_break.ogg"
define sfx.door_open = "audio/sfx/door_close.ogg"
define sfx.drop clothes = "audio/sfx/drop_clothes.ogg"
define sfx.forest_footsteps = "audio/sfx/forest_footsteps.ogg"
define sfx.footsteps_snow = "audio/sfx/footsteps_snow.ogg"
define sfx.footsteps_snowf = "audio/sfx/footsteps_snowf.ogg"
define sfx.galeblast = "audio/sfx/galeblast.ogg"
define sfx.glass_break = "audio/sfx/glass_break.ogg"
define sfx.grapple = "audio/sfx/grapple.ogg"
define sfx.heavy_bam = "audio/sfx/heavy_bam.ogg"
define sfx.heavy_crash = "audio/sfx/heavy_crash.ogg"
define sfx.heavy_slash = "audio/sfx/heavy_slash.ogg"
define sfx.hurl = "audio/sfx/hurl.ogg"
define sfx.jab = "audio/sfx/jab.ogg"
define sfx.kiss = "audio/sfx/kiss.ogg"
define sfx.light_grapple = "audio/sfx/light_grapple.ogg"
define sfx.lunge = "audio/sfx/lunge.ogg" 
define sfx.kathunk = "audio/sfx/kathunk.ogg"
define sfx.knock_and_open = "audio/sfx/knock_and_open.ogg"
define sfx.mana_charge = "audio/sfx/mana_charge.ogg"
define sfx.mana_explosion = "audio/sfx/mana_explosion.ogg"
define sfx.melee_swing = "audio/sfx/melee_swing.ogg"
define sfx.parry = "audio/sfx/parry.ogg"
define sfx.pottery_break = "audio/sfx/potterycrash.ogg"
define sfx.rapidfirepunch = "audio/sfx/rapidfirepunch.ogg"
define sfx.singe = "audio/sfx/singe.ogg"
define sfx.slash = "audio/sfx/slash.ogg"
define sfx.stab = "audio/sfx/stab.ogg"
define sfx.thud = "audio/sfx/thud.ogg"
define sfx.weapon_draw = "audio/sfx/weapon_draw.ogg"
define sfx.weapon_swing = "audio/sfx/weapon_swing.ogg"
define sfx.weapon_swingh = "audio/sfx/weapon_swingh.ogg"
define sfx.whoosh = "audio/sfx/whoosh.ogg"
define sfx.wood_break = "audio/sfx/wood_break.ogg"
define sfx.zap = "audio/sfx/zap.ogg"